FROM node:18 as BUILD

RUN mkdir /app
WORKDIR /app

COPY . /app
COPY ./package.json /app/package.json

WORKDIR /app

RUN npm i -g pnpm
RUN pnpm -r i

RUN pnpm run build
RUN sed -i '/\"devDependencies\"/,/}/ d; /^$/d' package.json
RUN cp package.json build/package.json

FROM node:18

COPY --from=build /app/build /opt/build
COPY --from=build /app/package.json /opt/build/package.json

WORKDIR /opt/build

EXPOSE ${PORT}

CMD node index.js
