FROM node:14-alpine
RUN apk add git
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
# COPY package-lock.json ./
COPY . ./
RUN npm install
RUN ls
RUN npm run build

EXPOSE ${PORT}
EXPOSE 3001

CMD npm run start