export const GET_OFFER_MESSAGES = Symbol('GET_OFFER_MESSAGES');
export const GOT_OFFER_MESSAGES = Symbol('GOT_OFFER_MESSAGES');
export const GET_OFFER_MESSAGES_FAILED = Symbol('GET_OFFER_MESSAGES_FAILED');

export const GET_OFFER_MESSAGE = Symbol('GET_OFFER_MESSAGE');
export const GOT_OFFER_MESSAGE = Symbol('GOT_OFFER_MESSAGE');
export const GET_OFFER_MESSAGE_FAILED = Symbol('GET_OFFER_MESSAGE_FAILED');

export const GET_CONTACT_MESSAGES = Symbol('GET_CONTACT_MESSAGES');
export const GOT_CONTACT_MESSAGES = Symbol('GOT_CONTACT_MESSAGES');
export const GET_CONTACT_MESSAGES_FAILED = Symbol('GET_CONTACT_MESSAGES_FAILED');

export const GET_CONTACT_MESSAGE = Symbol('GET_CONTACT_MESSAGE');
export const GOT_CONTACT_MESSAGE = Symbol('GOT_CONTACT_MESSAGE');
export const GET_CONTACT_MESSAGE_FAILED = Symbol('GET_CONTACT_MESSAGE_FAILED');
